Various small fixes (fock plots, default matmul precision, directory structure) (#580)
* Set default matmul precision to "highest"

JAX's default setting is device-dependent.

* Fix integer_ticks() bug in plots utils

The previous version would raise
> TypeError: set_params() got an unexpected keyword argument 'integer'
in some situations.

* Better defaults for plot_fock* allxticks and allyticks

Matplotlib's default is better than having always all ticks on, whichs
renders badly for Hilbert space with n > 32.

* Add label argument to plot_fock

For super-imposed Fock population plots. I didn't modify the doc example
to keep it short.

* Fix plot_fock_evolution example

* Fix plot_fock_evolution number of colors for logscale

Previous example was rounding
> jnp.log10(1 / 1e-4)  # Array(3.9999998, dtype=float32)
to 3 instead of 4.

* Remove include/ directory from root directory